CREATE TABLE IF NOT EXISTS tracks (
  -- TODO: 改成 UUID
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ip inet NOT NULL,
  from_url varchar(500) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

